trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  deployPath: '\\testing-server\c$\Inetpub\wwwroot\YourWebApp'
  serviceConnection: 'YourServiceConnectionName'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - script: |
        # Your build steps here
        echo "Building the application"
      displayName: 'Build'

- stage: Deploy
  displayName: 'Deploy Stage'
  jobs:
  - job: Deploy
    displayName: 'Deploy Job'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        version: '3.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: DotNetCoreCLI@2
      displayName: 'Restore and Publish'
      inputs:
        command: 'publish'
        publishWebProjects: true
        projects: '$(solution)'
        arguments: '-o $(Build.ArtifactStagingDirectory)/publish'
        zipAfterPublish: true

    - task: CopyFiles@2
      displayName: 'Copy Files to Deploy Path'
      inputs:
        SourceFolder: '$(Build.ArtifactStagingDirectory)/publish'
        Contents: '**'
        TargetFolder: '$(System.ArtifactsDirectory)/publish'

    - task: PowerShell@2
      displayName: 'Deploy to Testing Server'
      inputs:
        targetType: 'inline'
        script: |
          # Copy files to the testing server using the service connection
          Copy-Item -Path $(System.ArtifactsDirectory)/publish/* -Destination $(deployPath) -Recurse
      env:
        PSModulePath: $(PSModulePath)

    - task: CopyFiles@2
      displayName: 'Copy Files to Testing Server'
      inputs:
        SourceFolder: '$(System.ArtifactsDirectory)/publish'
        Contents: '**'
        TargetFolder: '$(deployPath)'